project_id = "pkqjareakzazzwttxqjl"

[functions.create-onboarding-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.retrieve-checkout-email]
verify_jwt = false

[functions.sync-team-squads]
verify_jwt = false
